---

# # Basic Lambda function deletion
# - name: Delete Lambda functions HelloWorld and ByeBye
#   lambda:
#     name: '{{ item }}'
#     state: absent
#   with_items:
#     - HelloWorld
#     - ByeBye